### ISSUE TITLE
Question on conversion file format

### ISSUE THREAD

**Issue by rgieseke** [pik-primap/climate_categories#48]
Hi Mika.

It's probably a bit of bike-shedding but i wanted to ask about the conversion file format (before it's too widespread to eve change :smile: ).
It's not a 'valid' CSV as it consists of two CSV sections separated by a blank line.
The first section is meta data so i wonder whether a format like below could work:

```
# references: IPCC 2006, 2006 IPCC Guidelines for National Greenhouse Gas Inventories, Prepared by the National Greenhouse Gas Inventories Programme, Eggleston H.S., Buendia L., Miwa K., Ngara T. and Tanabe K. (eds). Volume 1, Chapter 8, Table 8.2 https://www.ipcc-nggip.iges.or.jp/public/2006gl/vol1.html
# institution: IPCC
# last_update: 2021-07-09
IPCC1996,gas,IPCC2006,comment
0,,0,
1,,1,
1.A,,1.A,
1.A.1,,1.A.1,
```
The actual data could be read with Pandas `read_csv`'s `comment='#'` option, the rest would require some custom code.

**Comment by mikapfl** [comment]
The goal here was that the CSV can be directly read using excel. A quick test shows that a header like you describe with a comment character works as well in excel, and would make reading it with e.g. pandas easier, true. Note however that actually reading it to do something with it (rather than just looking at it quickly using excel because the display is nice) needs rather sophisticated parsing because codes can contain commas (the real world hurts) and therefore the escaping rules need to be followed strictly.

So: I'm fine with changing the format to using a commenting character, but escaping rules (also for the commenting character) need to be specified, and don't expect pandas' `read_csv` to be able to read the actual data in all circumstances.

**Comment by rgieseke** [comment]
So would you be fine with the header being (strict) YAML with lines beginning with comment '#' and the rest being CSV?

There have been projects (e.g. metacsv https://github.com/ClimateImpactLab/metacsv) using a YAML header, but i'm not a fan of the YAML header format without comment chars as this prevents using a simple `read_csv` call.

Going into this direction is a much better approach i think: https://github.com/leeper/csvy
(Without necessarily having to follow any of these specs exactly, just as examples.)

**Comment by mikapfl** [comment]
Yes, what you propose sounds very reasonable.
